adminPanel/admin_panel/urls.py
from django.conf.urls import url

from . import views

app_name = 'admin_panel'

urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^factory/(?P<factoryId>[0-9]+)/details/$', views.factoryDetails, name='factoryDetails'),
    url(r'^factory/add/$', views.addFactory, name='addFactory'),
    url(r'^factory/(?P<factoryId>[0-9]+)/remove/$', views.removeFactory, name='removeFactory'),
    url(r'^factory/(?P<factoryId>[0-9]+)/update/$', views.updateFactory, name='updateFactory'),
    url(r'^factory/(?P<factoryId>[0-9]+)/stream/$', views.factoryStream, name='factoryStream'),
    url(r'^factory/(?P<factoryId>[0-9]+)/analysis/$', views.factoryAnalysis, name='factoryAnalysis'),

    url(r'^employee/(?P<employeeId>[0-9]+)/details/$', views.employeeDetails, name='employeeDetails'),
    url(r'^employee/(?P<employeeId>[0-9]+)/update/$', views.updateEmployee, name='updateEmployee'),
    url(r'^factory/(?P<factoryId>[0-9]+)/employee/(?P<employeeId>[0-9]+)/remove/$', views.removeEmployee, name='removeEmployee'),
    url(r'^employee/add/$', views.addEmployee, name='addEmployee'),
    url(r'^employee/(?P<employeeId>[0-9]+)/entitlement/add/$', views.addEntitlementToEmployee, name='addEntitlementToEmployee'),
    url(r'^employee/(?P<employeeId>[0-9]+)/entitlement/remove/$', views.removeEntitlementFromEmployee, name='removeEntitlementFromEmployee'),
    url(r'^employee/(?P<employeeId>[0-9]+)/move/$', views.moveEmployeeToAnotherFactory, name='moveEmployeeToAnotherFactory'),

    url(r'^entitlement/add/$', views.addEntitlement, name='addEntitlement'),
    url(r'^entitlement/(?P<entitlementId>[0-9]+)/remove/$', views.removeEntitlement, name='removeEntitlement'),
    url(r'^entitlement/(?P<entitlementId>[0-9]+)/update/$', views.updateEntitlement, name='updateEntitlement'),

    url(r'^machine/add/$', views.addMachine, name='addMachine'),
    url(r'^machine/(?P<machineId>[0-9]+)/details/$', views.machineDetails, name='machineDetails'),
    url(r'^factory/(?P<factoryId>[0-9]+)/machine/(?P<machineId>[0-9]+)/remove/$', views.removeMachine, name='removeMachine'),
    url(r'^machine/(?P<machineId>[0-9]+)/update/$', views.updateMachine, name='updateMachine'),
    url(r'^machine/(?P<machineId>[0-9]+)/entitlement/add/$', views.addEntitlementToMachine, name='addEntitlementToMachine'),
    url(r'^machine/(?P<machineId>[0-9]+)/entitlement/remove/$', views.removeEntitlementFromMachine, name='removeEntitlementFromMachine'),

    url(r'^factory/(?P<factoryId>[0-9]+)/map/view/$', views.viewMap, name='viewMap'),
    url(r'^factory/(?P<factoryId>[0-9]+)/map/reset/$', views.resetMap, name='resetMap'),

#AJAX

    url(r'^ajax/factory/(?P<factoryId>[0-9]+)/map/get/$', views.getMap, name='getMap'),
    url(r'^ajax/factory/(?P<factoryId>[0-9]+)/map/sector/add/$', views.addSector, name='addSector'),
    url(r'^ajax/factory/(?P<factoryId>[0-9]+)/map/sector/get/(?P<sectorId>[0-9]+)/$', views.getSector, name='getSector'),
    url(r'^ajax/factory/(?P<factoryId>[0-9]+)/map/sector/delete/(?P<sectorId>[0-9]+)/$', views.deleteSector, name='deleteSector'),
    url(r'^ajax/factory/(?P<factoryId>[0-9]+)/analysis/get/$', views.getAnalysis, name='getAnalysis'),

]

adminPanel/web/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^admin_panel/', include("admin_panel.urls")),
]

adminPanel/admin_panel/models.py
from django.db import models


class Employee(models.Model):
    id = models.IntegerField(unique=True, primary_key=True)
    firstname = models.CharField(db_column='firstName', max_length=255)  # Field name made lowercase.
    lastname = models.CharField(db_column='lastName', max_length=255)  # Field name made lowercase.
    email = models.CharField(max_length=255)
    phone = models.CharField(max_length=32)
    factory = models.ForeignKey('Factory', models.DO_NOTHING, db_column='factory')

    class Meta:
        managed = False
        db_table = 'Employee'


class Employeeentitlement(models.Model):
    id = models.IntegerField(unique=True, primary_key=True)
    employee = models.ForeignKey(Employee, models.DO_NOTHING, db_column='employee')
    entitlement = models.ForeignKey('Entitlement', models.DO_NOTHING, db_column='entitlement')

    class Meta:
        managed = False
        db_table = 'EmployeeEntitlement'


class Entitlement(models.Model):
    id = models.IntegerField(unique=True, primary_key=True)
    name = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'Entitlement'


class Factory(models.Model):
    id = models.IntegerField(unique=True, primary_key=True)
    address = models.TextField()
    workinghours = models.IntegerField(db_column='workingHours')  # Field name made lowercase.
    restinghours = models.IntegerField(db_column='restingHours')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Factory'


class Factorymap(models.Model):
    id = models.IntegerField(unique=True, primary_key=True)
    factory = models.ForeignKey(Factory, models.DO_NOTHING, db_column='factory', unique=True)
    width = models.IntegerField()
    height = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'FactoryMap'


class Factorymapsector(models.Model):
    id = models.IntegerField(unique=True, primary_key=True)
    factorymap = models.ForeignKey(Factorymap, models.DO_NOTHING, db_column='factoryMap')  # Field name made lowercase.
    width = models.IntegerField()
    height = models.IntegerField()
    machine = models.ForeignKey('Machine', models.DO_NOTHING, db_column='machine')
    x = models.IntegerField()
    y = models.IntegerField()
    priority = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'FactoryMapSector'


class Machine(models.Model):
    id = models.IntegerField(unique=True, primary_key=True)
    name = models.CharField(max_length=255)
    factory = models.ForeignKey(Factory, models.DO_NOTHING, db_column='factory')
    workingplaces = models.IntegerField(db_column='workingPlaces')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Machine'


class Machineentitlementrequired(models.Model):
    id = models.IntegerField(unique=True, primary_key=True)
    machine = models.ForeignKey(Machine, models.DO_NOTHING, db_column='machine')
    entitlementrequired = models.ForeignKey(Entitlement, models.DO_NOTHING, db_column='entitlementRequired')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'MachineEntitlementRequired'


class Report(models.Model):
    id = models.IntegerField(unique=True, primary_key=True)
    date = models.TextField()  # This field type is a guess.
    factory = models.ForeignKey(Factory, models.DO_NOTHING, db_column='factory')
    employee = models.ForeignKey(Employee, models.DO_NOTHING, db_column='employee')
    sector = models.ForeignKey(Factorymapsector, models.DO_NOTHING, db_column='sector')
    period = models.IntegerField()
    maxperiod = models.IntegerField(db_column='maxPeriod')  # Field name made lowercase.
    workingplaces = models.IntegerField(db_column='workingPlaces')  # Field name made lowercase.
    totalworkingplaces = models.IntegerField(db_column='totalWorkingPlaces')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Report'


class Workingplace(models.Model):
    id = models.IntegerField(unique=True, primary_key=True)
    sector = models.ForeignKey(Factorymapsector, models.DO_NOTHING, db_column='sector')
    occupiedby = models.ForeignKey(Employee, models.DO_NOTHING, db_column='occupiedBy', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'WorkingPlace'

adminPanel/admin_panel/views.py
from django.shortcuts import render
from admin_panel.models import *
from admin_panel.tools import dataValidation, analysis, dbTools
from django.http import HttpResponseRedirect
from django.urls import reverse
import json
from django.http import HttpResponse
from django.core import serializers


##		VARIABLES	###

DEFAULT_MAP_WIDTH = 10
DEFAULT_MAP_HEIGHT = 10

###		GET 	###
from django.views.decorators.cache import never_cache

@never_cache
def index(request):
	return render(request, 'index.html', {
		"factories": Factory.objects.all(),
		"entitlements": Entitlement.objects.all()
	})

@never_cache
def factoryDetails(request, factoryId):
	try:
		factory = Factory.objects.get(id=factoryId)
		machines = []
		try:
			machines = Machine.objects.filter(factory=factoryId)
		except Machine.DoesNotExist:
			pass
		employees = []
		try:
			employees = Employee.objects.filter(factory=factoryId)
		except Employee.DoesNotExist:
			pass
		return render(request, 'factoryDetails.html', { 
			"factory":  factory,
			"machines": machines,
			"employees": employees
		})
	except Factory.DoesNotExist:
		return HttpResponseRedirect(reverse('admin_panel:index'))


@never_cache
def machineDetails(request, machineId):
	try:
		machine = Machine.objects.get(id=machineId)
		factory = Factory.objects.get(id=machine.factory.id)
		machineEntitlementsIds = []
		machineEntitlements = set(Machineentitlementrequired.objects.filter(machine=machineId))
		for entitlement in machineEntitlements:
			machineEntitlementsIds.append(entitlement.entitlementrequired.id)
		unusedEntitlements = Entitlement.objects.exclude(id__in=machineEntitlementsIds)
		machineEntitlements = Entitlement.objects.filter(id__in=machineEntitlementsIds)
		return render(request, 'machineDetails.html', {
			"machine": machine,
			"factory": factory,
			"machineEntitlements": machineEntitlements,
			"unusedEntitlements": unusedEntitlements
		})
	except (Factory.DoesNotExist, Machine.DoesNotExist):
		return HttpResponseRedirect(reverse('admin_panel:index'))


@never_cache
def employeeDetails(request, employeeId):
	try:
		employee = Employee.objects.get(id=employeeId)
		factory = Factory.objects.get(id=employee.factory.id)
		empoyeeEntitlements = set(Employeeentitlement.objects.filter(employee=employeeId))
		empoyeeEntitlementsIds = []
		for entitlement in empoyeeEntitlements:
			empoyeeEntitlementsIds.append(entitlement.entitlement.id)
		unusedEntitlements = Entitlement.objects.exclude(id__in=empoyeeEntitlementsIds)
		empoyeeEntitlements = Entitlement.objects.filter(id__in=empoyeeEntitlementsIds)
		otherFactories = Factory.objects.exclude(id=factory.id)
		return render(request, 'employeeDetails.html', {
			"employee": employee,
			"factory": factory,
			"empoyeeEntitlements": empoyeeEntitlements,
			"unusedEntitlements": unusedEntitlements,
			"otherFactories": otherFactories
		})
	except (Factory.DoesNotExist, Employee.DoesNotExist):
		return HttpResponseRedirect(reverse('admin_panel:index'))

@never_cache
def viewMap(request, factoryId):
	try:
		factory = Factory.objects.get(id=factoryId)
		machines = []
		width = DEFAULT_MAP_WIDTH
		height = DEFAULT_MAP_HEIGHT
		try:
			factoryMap = Factorymap.objects.get(factory=factory)
			width = factoryMap.width
			height = factoryMap.height
		except Factorymap.DoesNotExist:
			Factorymap(factory = factory, width = DEFAULT_MAP_WIDTH, height = DEFAULT_MAP_HEIGHT).save()
		try:
			machines = Machine.objects.filter(factory=factoryId)
		except Machine.DoesNotExist:
			pass
		return render(request, 'map.html', { 
			"factory":  factory,
			"machines": machines,
			"width": width,
			"height": height,
		})
	except Factory.DoesNotExist:
		return HttpResponseRedirect(reverse('admin_panel:index'))

@never_cache
def factoryStream(request, factoryId):
	try:
		factory = Factory.objects.get(id=factoryId)
		otherFactories = Factory.objects.exclude(id=factory.id)
		return render(request, 'factoryStream.html', { 
			"factory":  factory,
			"otherFactories": otherFactories
		})
	except Factory.DoesNotExist:
		return HttpResponseRedirect(reverse('admin_panel:index'))

@never_cache
def factoryAnalysis(request, factoryId):
	try:
		factory = Factory.objects.get(id=factoryId)
		analysis.updateDatabase()
		reports = Report.objects.filter(factory=factory).order_by().values('date').distinct()
		reports = [{'readable': analysis.getDate(r['date']), 'value': r['date']} for r in reports]
		return render(request, 'factoryAnalysis.html', { 
			"factory":  factory,
			"reports": reports,
		})
	except Factory.DoesNotExist:
		return HttpResponseRedirect(reverse('admin_panel:index'))

###		POST 	###

#FACTORY

def addFactory(request):
	address = request.POST.get("address", "")
	workingHours = request.POST.get("workinghours", "")
	restingHours = request.POST.get("restinghours", "")
	if len(address) > 0 and len(workingHours) > 0 and len(restingHours) > 0:
		workingHours = int(workingHours)
		restingHours = int(restingHours)
		if workingHours > restingHours:
			Factory(address=address, workinghours=workingHours, restinghours=restingHours).save()
	return HttpResponseRedirect(reverse('admin_panel:index'))

def removeFactory(request, factoryId):
	try:
		factory = Factory.objects.get(id=factoryId)
		machines = Machine.objects.filter(factory=factory)
		for machine in machines:
			Machineentitlementrequired.objects.filter(machine=machine).delete()
			machine.delete()
		maps = Factorymap.objects.filter(factory=factory)
		for mp in maps:
			sectors = Factorymapsector.objects.filter(factorymap=mp)
			for sector in sectors:
				workingPlaces = Workingplace.objects.filter(sector=sector)
				for workingPlace in workingPlaces:
					workingPlace.delete()
				sector.delete()
			mp.delete()
		employees = Employee.objects.filter(factory=factory)
		for employee in employees:
			Employeeentitlement.objects.filter(employee=employee).delete()
			employee.delete()
		factory.delete()
	except Factory.DoesNotExist:
		pass
	return HttpResponseRedirect(reverse('admin_panel:index'))

def updateFactory(request, factoryId):
	try:
		address = request.POST.get("address","")
		workingHours = request.POST.get("workinghours","")
		restingHours = request.POST.get("restinghours","")
		factory = Factory.objects.get(id=factoryId)
		if len(address) > 0 and len(workingHours) > 0 and len(restingHours) > 0:
			workingHours = int(workingHours)
			restingHours = int(restingHours)
			if workingHours > restingHours:
				factory.workinghours = workingHours
				factory.restinghours = restingHours
			factory.address = address
		factory.save()
	except Factory.DoesNotExist:
		return HttpResponseRedirect(reverse('admin_panel:index'))
	return HttpResponseRedirect(reverse('admin_panel:factoryDetails', args=(factoryId,)))

#EMPLOYEE

def addEmployee(request):
	firstname = request.POST.get("firstname", "")
	lastname = request.POST.get("lastname", "")
	email = request.POST.get("email", "")
	phone = request.POST.get("phone", "")
	factoryId = int(request.POST.get("factory", 0))
	if dataValidation.validateUserData(firstname, lastname, email, phone):
		try:
			factory = Factory.objects.get(id=factoryId)
			Employee(firstname=firstname, lastname=lastname, email=email, phone=phone, factory=factory).save()
		except Factory.DoesNotExist:
			return HttpResponseRedirect(reverse('admin_panel:index'))
	return HttpResponseRedirect(reverse('admin_panel:factoryDetails', args=(factoryId,)))

def updateEmployee(request, employeeId):
	try:
		firstname = request.POST.get("firstname","")
		lastname = request.POST.get("lastname","")
		email = request.POST.get("email","")
		phone = request.POST.get("phone","")
		if dataValidation.validateUserData(firstname, lastname, email, phone):
			employee = Employee.objects.get(id=employeeId)
			employee.firstname = firstname
			employee.lastname = lastname
			employee.email = email
			employee.phone = phone
			employee.save()
	except Employee.DoesNotExist:
		return HttpResponseRedirect(reverse('admin_panel:index'))
	return HttpResponseRedirect(reverse('admin_panel:employeeDetails', args=(employeeId,)))

def moveEmployeeToAnotherFactory(request, employeeId):
	try:
		factoryId = int(request.POST.get("factory",0))
		if factoryId != 0:
			factory = Factory.objects.get(id=factoryId)
			employee = Employee.objects.get(id=employeeId)
			employee.factory = factory
			employee.save()
	except (Employee.DoesNotExist, Factory.DoesNotExist):
		return HttpResponseRedirect(reverse('admin_panel:index'))
	return HttpResponseRedirect(reverse('admin_panel:employeeDetails', args=(employeeId,)))

def removeEmployee(request, factoryId, employeeId):
	try:
		employee = Employee.objects.get(id=employeeId)
		entitlements = Employeeentitlement.objects.filter(employee=employee)
		for ent in entitlements:
			ent.delete()
		employee.delete()
	except Employee.DoesNotExist:
		return HttpResponseRedirect(reverse('admin_panel:index'))
	return HttpResponseRedirect(reverse('admin_panel:factoryDetails', args=(factoryId,)))

def addEntitlementToEmployee(request, employeeId):
	entitlementId = request.POST.get("entitlement", 0)
	try:
		entitlement = Entitlement.objects.get(id=entitlementId)
		employee = Employee.objects.get(id=employeeId)
		Employeeentitlement(employee=employee, entitlement=entitlement).save()
	except Entitlement.DoesNotExist:
		pass
	except Employee.DoesNotExist:
		return HttpResponseRedirect(reverse('admin_panel:index'))
	return HttpResponseRedirect(reverse('admin_panel:employeeDetails', args=(employeeId,)))

def removeEntitlementFromEmployee(request, employeeId):
	entitlementId = request.POST.get("entitlement", 0)
	try:
		entitlement = Entitlement.objects.get(id=entitlementId)
		employee = Employee.objects.get(id=employeeId)
		Employeeentitlement.objects.get(employee=employee, entitlement=entitlement).delete()
	except (Entitlement.DoesNotExist, Employeeentitlement.DoesNotExist):
		pass
	except Employee.DoesNotExist:
		return HttpResponseRedirect(reverse('admin_panel:index'))

adminPanel/admin_panel/templates/base.html
<html>
	<head>
		<title>admin panel home</title>

		{% load static %}
		<link rel="stylesheet" type="text/css" href="{% static 'libs/bootstrap/css/bootstrap.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'css/global.css' %}" />
		{% block styles %}
		{% endblock %}

	</head>

	<body>
		<div class="row">
			<div class="col-xs-12">
				<h1>{{ factory.address }}</h1>
			</div>
		</div>
		<section id="content-section">
			<div class="container">
				{% block content %}
				{% endblock %}
			</div>
		</section>

		<section id="section-scripts">
			<script src="{% static 'libs/jquery.min.js' %}"></script>
			{% block scripts %}
			{% endblock %}
		</section>
		<div class="row">
			<div class="col-xs-12">
				<hr />
			</div>
		</div>

	</body>
</html>

adminPanel/admin_panel/templates/employeeDetails.html
{% extends "base.html" %}

{% load static %}

{% block styles %}
{% endblock %}

{% block scripts %}
	<script src="{% static 'js/adding.js' %}"></script>
{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-xs-12">
			<a href="{% url 'admin_panel:index' %}">home</a>
			<span class="glyphicon glyphicon-arrow-right"></span>
			<a href="{% url 'admin_panel:factoryDetails' factory.id %}">factory details</a>
			<span class="glyphicon glyphicon-arrow-right"></span>
			employee details
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12">
			<form action="{% url 'admin_panel:updateEmployee' employee.id %}" method="post">
			{% csrf_token %}
				<table>
					<tr>
						<td>first name</td>
						<td>
							<input name="firstname" value="{{ employee.firstname }}" />
						</td>
					</tr>
					<tr>
						<td>last name</td>
						<td>
							<input name="lastname" value="{{ employee.lastname }}" />
						</td>
					</tr>
					<tr>
						<td>email</td>
						<td>
							<input name="email" value="{{ employee.email }}" />
						</td>
					</tr>
					<tr>
						<td>phone</td>
						<td>
							<input name="phone" value="{{ employee.phone }}" />
						</td>
					</tr>
				</table>
				<br />
				<input type="submit" value="update" />
			</form>
		</div>


		<div class="col-xs-12">
			<form action="{% url 'admin_panel:removeEmployee' factory.id employee.id %}" method="post">
			{% csrf_token %}
				<input type="submit" value="remove" />
			</form>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-12">
			<h2>entitlements</h2>
		</div>
		<div class="col-xs-12">
			<div class="row">
				{% for entitlement in empoyeeEntitlements %}
						<div class="col-xs-6 cols-sm-4 col-md-3 tile">
							{{ entitlement.name }}
							<br />
							<form action="{% url 'admin_panel:removeEntitlementFromEmployee' employee.id %}" method="post">
							{% csrf_token %}
								<input type="hidden" name="entitlement" value="{{ entitlement.id }}">
								<input type="submit" value="remove" />
							</form>
						</div>
				{% endfor %}
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-6 cols-sm-4 col-md-3 tile">
			<p id="roll-adding-form-entitlement" class="roll-adding-form glyphicon glyphicon-plus"></p>
			<form id="adding-form-entitlement" class="adding-form" action="{% url 'admin_panel:addEntitlementToEmployee' employee.id %}" method="post">
			{% csrf_token %}
				<select name="entitlement">
					{% for entitlement in unusedEntitlements %}
						<option value="{{ entitlement.id }}">{{ entitlement.name }}</option>
					{% endfor %}
				</select>
				<input type="submit" value="add" />
			</form>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-12">
			move to another factory:<br />
			<form id="move-employee" action="{% url 'admin_panel:moveEmployeeToAnotherFactory' employee.id %}" method="post">
			{% csrf_token %}
				<select name="factory">
					{% for otherFactory in otherFactories %}
						<option value="{{ otherFactory.id }}">{{ otherFactory.address }}</option>
					{% endfor %}
				</select>
				<br />
				<input type="submit" value="move" />
			</form>
		</div>
	</div>

{% endblock %}

adminPanel/admin_panel/templates/factoryDetails.html
{% extends "base.html" %}

{% load static %}

{% block styles %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/factoryDetails.css' %}" />
{% endblock %}

{% block scripts %}
	<script src="{% static 'js/adding.js' %}"></script>
{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-xs-12">
			<a href="{% url 'admin_panel:index' %}">home</a>
			<span class="glyphicon glyphicon-arrow-right"></span>
			factory details
		</div>
	</div>
	<hr />
	<div class="row">
		<div class="col-xs-12">
			<a href="{% url 'admin_panel:factoryStream' factory.id %}">watch factory working</a>
		</div>
	</div>
	<hr />
	<div class="row">
		<div class="col-xs-12">
			<a href="{% url 'admin_panel:viewMap' factory.id %}">view map</a>
		</div>
	</div>
	<hr />
	<div class="row">
		<div class="col-xs-12">
			<a href="{% url 'admin_panel:factoryAnalysis' factory.id %}">factory analysis</a>
		</div>
	</div>
	<hr />
	<div class="row">
		<div class="col-xs-12">
			<form action="{% url 'admin_panel:updateFactory' factory.id %}" method="post">
			{% csrf_token %}
				<table>
					<tr>
						<td>address</td>
						<td>
							<input name="address" value="{{ factory.address }}" />
						</td>
					</tr>
					<tr>
						<td>working hours</td>
						<td><input type="number" min="1" max="24" name="workinghours" value="{{ factory.workinghours }}" /></td>
					</tr>
					<tr>
						<td>resting hours</td>
						<td><input type="number" min="1" max="24" name="restinghours" value="{{ factory.restinghours }}" /></td>
					</tr>
				</table>
				<br />
				<input type="submit" value="update" />
			</form>
		</div>
	</div>
	<hr />
	<div class="row">
		<div class="col-xs-12">
			<h2>machines</h2>
		</div>
		<div class="col-xs-12">
			<div class="row">
				{% for machine in machines %}
					<div class="col-xs-6 cols-sm-4 col-md-3	tile">
						<table>
							<tr>
								<td>name</td>
								<td>{{ machine.name }}</td>
							</tr>
							<tr>
								<td colspan="2">
									<a href="{% url 'admin_panel:machineDetails' machine.id %}">details</a>
								</td>
							</tr>
						</table>
					</div>
				{% endfor %}
			</div>
			<div class="row">
				<div class="col-xs-6 cols-sm-4 col-md-3	tile">
					<p id="roll-adding-form-machine" class="roll-adding-form glyphicon glyphicon-plus"></p>
					<form id="adding-form-machine" class="adding-form" action="{% url 'admin_panel:addMachine' %}" method="post">
					{% csrf_token %}
						<table>
							<tr>
								<td>name</td>
								<td><input name="name" /></td>
							</tr>
							<tr>
								<td>working places</td>
								<td><input name="workingplaces" type="number" min="1" value="1" /></td>
							</tr>
						</table>
						<input type="hidden" name="factory" value="{{ factory.id }}" />
						<input type="submit" value="add" />
					</form>
				</div>
			</div>
		</div>
	</div>
	<hr />
	<div class="row">
		<div class="col-xs-12">
			<h2>employees</h2>
		</div>
		<div class="col-xs-12">
			<div class="row">
				{% for employee in employees %}
					<div class="col-xs-6 cols-sm-4 col-md-3	tile">
						<table>
							<tr>
								<td>first name</td>
								<td>{{ employee.firstname }}</td>
							</tr>
							<tr>
								<td>last name</td>
								<td>{{ employee.lastname }}</td>
							</tr>
							<tr>
								<td>email</td>
								<td>{{ employee.email }}</td>
							</tr>
							<tr>
								<td>phone</td>
								<td>{{ employee.phone }}</td>
							</tr>
							<tr>
								<td colspan="2">
									<a href="{% url 'admin_panel:employeeDetails' employee.id %}">details</a>
								</td>
							</tr>
						</table>
					</div>
				{% endfor %}
			</div>
			<div class="row">
				<div class="col-xs-6 cols-sm-4 col-md-3	tile">
					<p id="roll-adding-form-employee" class="roll-adding-form glyphicon glyphicon-plus"></p>
					<form id="adding-form-employee" class="adding-form" action="{% url 'admin_panel:addEmployee' %}" method="post">
					{% csrf_token %}
						<table>
							<tr>
								<td>
									<span>first name</span>
								</td>
								<td>
									<input name="firstname" />
								</td>
							</tr>
							<tr>
								<td>
									<span>last name</span>
								</td>
								<td>
									<input name="lastname" />
								</td>
							</tr>
							<tr>
								<td>
									<span>email</span>
								</td>
								<td>
									<input name="email" />
								</td>
							</tr>
							<tr>
								<td>
									<span>phone</span>
								</td>
								<td>
									<input name="phone" />
								</td>
							</tr>
						</table>
						<input type="hidden" name="factory" value="{{ factory.id }}" />
						<input type="submit" value="add" />
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock %}